# Generated by Django 3.2.5 on 2021-07-30 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_rename_possibleansewr_possibleanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='possibleanswer',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='question',
            name='creator',
        ),
        migrations.AlterField(
            model_name='possibleanswer',
            name='body',
            field=models.CharField(max_length=500, verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='possibleanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='possible_answers', to='question.question', verbose_name='Question'),
        ),
    ]
