# Generated by Django 3.2.5 on 2021-07-29 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL, verbose_name='Participant')),
            ],
        ),
        migrations.CreateModel(
            name='GameQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='game.game', verbose_name='Game')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_questions', to='question.question', verbose_name='Question')),
                ('user_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_questions', to='question.possibleansewr', verbose_name='User answer')),
            ],
        ),
        migrations.AddConstraint(
            model_name='gamequestion',
            constraint=models.UniqueConstraint(fields=('game', 'question'), name='unique_game_quesions'),
        ),
    ]
