# Generated by Django 3.2.5 on 2021-07-30 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20210730_2053'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamequestion',
            name='user_answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_questions', to='question.possibleanswer', verbose_name='User answer'),
        ),
    ]
