# Generated by Django 3.2.5 on 2021-07-30 21:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_gamequestion_user_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamequestion',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created Date'),
            preserve_default=False,
        ),
    ]
