# Generated by Django 3.2.5 on 2021-07-30 21:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_gamequestion_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamequestion',
            name='created_date',
        ),
        migrations.AddField(
            model_name='game',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created Date'),
            preserve_default=False,
        ),
    ]
