# Generated by Django 3.2.5 on 2021-07-30 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20210730_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='finished_date',
            field=models.DateTimeField(null=True, verbose_name='Finished Date'),
        ),
    ]
