# Generated by Django 3.2.5 on 2021-07-30 21:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_game_finished_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamequestion',
            name='final_score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(0)], verbose_name='Final Score'),
        ),
    ]
